from .nodes import NODE_CLASS_MAPPINGS as NS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NS_DISPLAY
from .nodes_voice_generator import NODE_CLASS_MAPPINGS as NV_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NV_DISPLAY

NODE_CLASS_MAPPINGS = {**NS_MAPPINGS, **NV_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NS_DISPLAY, **NV_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
